-- ============================

-- Diese Datei wurde mit dem Derby-Utility dblook erstellt.
-- Zeitstempel: 2022-12-13 08:02:15.409
-- Quelldatenbank: /tmp/archiva-blöd/data/users
-- Verbindungs-URL: jdbc:derby:/tmp/archiva-blöd/data/users
-- appendLogs: false

-- ----------------------------------------------
-- DDL-Anweisungen für Schemas
-- ----------------------------------------------

CREATE SCHEMA "SA";

-- ----------------------------------------------
-- DDL-Anweisungen für Funktionen
-- ----------------------------------------------

CREATE FUNCTION "SA"."JPOX_ASCII" ("C" CHAR(1)) RETURNS INTEGER LANGUAGE JAVA PARAMETER STYLE JAVA READS SQL DATA CALLED ON NULL INPUT EXTERNAL NAME 'org.jpox.store.rdbms.adapter.DerbySQLFunction.ascii' ;

CREATE FUNCTION "SA"."JPOX_MATCHES" ("TEXT" VARCHAR(8000),"PATTERN" VARCHAR(8000)) RETURNS INTEGER LANGUAGE JAVA PARAMETER STYLE JAVA READS SQL DATA CALLED ON NULL INPUT EXTERNAL NAME 'org.jpox.store.rdbms.adapter.DerbySQLFunction.matches' ;

-- ----------------------------------------------
-- DDL-Anweisungen für Tabellen
-- ----------------------------------------------

CREATE TABLE "SA"."SECURITY_PERMISSIONS" ("NAME" VARCHAR(255) NOT NULL, "DESCRIPTION" VARCHAR(255), "OPERATION_NAME_OID" VARCHAR(255), "PERMANENT" CHAR(1) NOT NULL, "RESOURCE_IDENTIFIER_OID" VARCHAR(255));

CREATE TABLE "SA"."SECURITY_ROLES" ("NAME" VARCHAR(255) NOT NULL, "ASSIGNABLE" CHAR(1) NOT NULL, "DESCRIPTION" VARCHAR(255), "PERMANENT" CHAR(1) NOT NULL);

CREATE TABLE "SA"."SECURITY_RESOURCES" ("IDENTIFIER" VARCHAR(255) NOT NULL, "PATTERN" CHAR(1) NOT NULL, "PERMANENT" CHAR(1) NOT NULL);

CREATE TABLE "SA"."JDOUSER" ("USERNAME" VARCHAR(255) NOT NULL, "ACCOUNT_CREATION_DATE" TIMESTAMP, "COUNT_FAILED_LOGIN_ATTEMPTS" INTEGER NOT NULL, "EMAIL" VARCHAR(255), "ENCODED_PASSWORD" VARCHAR(255), "FULL_NAME" VARCHAR(255), "LAST_LOGIN_DATE" TIMESTAMP, "LAST_PASSWORD_CHANGE" TIMESTAMP, "LOCKED" CHAR(1) NOT NULL, "USER_PASSWORD" VARCHAR(255), "PASSWORD_CHANGE_REQUIRED" CHAR(1) NOT NULL, "PERMANENT" CHAR(1) NOT NULL, "VALIDATED" CHAR(1) NOT NULL);

CREATE TABLE "SA"."JDOUSER_PREVIOUSENCODEDPASSWORDS" ("USERNAME_OID" VARCHAR(255) NOT NULL, "STRING_ELE" VARCHAR(255), "INTEGER_IDX" INTEGER NOT NULL);

CREATE TABLE "SA"."SECURITY_USER_ASSIGNMENTS" ("PRINCIPAL" VARCHAR(255) NOT NULL, "PERMANENT" CHAR(1) NOT NULL, "LAST_UPDATED" TIMESTAMP);

CREATE TABLE "SA"."SECURITY_USERASSIGNMENT_ROLENAMES" ("PRINCIPAL_OID" VARCHAR(255) NOT NULL, "STRING_ELE" VARCHAR(255), "INTEGER_IDX" INTEGER NOT NULL);

CREATE TABLE "SA"."SECURITY_OPERATIONS" ("NAME" VARCHAR(255) NOT NULL, "DESCRIPTION" VARCHAR(255), "PERMANENT" CHAR(1) NOT NULL, "RESOURCE_REQUIRED" CHAR(1) NOT NULL);

CREATE TABLE "SA"."SECURITY_ROLE_PERMISSION_MAP" ("NAME_OID" VARCHAR(255) NOT NULL, "NAME_EID" VARCHAR(255), "INTEGER_IDX" INTEGER NOT NULL);

CREATE TABLE "SA"."SECURITY_ROLE_CHILDROLE_MAP" ("NAME_OID" VARCHAR(255) NOT NULL, "STRING_ELE" VARCHAR(255), "INTEGER_IDX" INTEGER NOT NULL);

-- ----------------------------------------------
-- DDL-Anweisungen für Schlüssel
-- ----------------------------------------------

-- PRIMARY/UNIQUE
ALTER TABLE "SA"."JDOUSER" ADD CONSTRAINT "JDOUSER_PK" PRIMARY KEY ("USERNAME");

ALTER TABLE "SA"."SECURITY_ROLES" ADD CONSTRAINT "SECURITY_ROLES_PK" PRIMARY KEY ("NAME");

ALTER TABLE "SA"."JDOUSER_PREVIOUSENCODEDPASSWORDS" ADD CONSTRAINT "JDOUSER_PREVIY7_PK" PRIMARY KEY ("USERNAME_OID", "INTEGER_IDX");

ALTER TABLE "SA"."SECURITY_PERMISSIONS" ADD CONSTRAINT "SECURITY_PERM77_PK" PRIMARY KEY ("NAME");

ALTER TABLE "SA"."SECURITY_ROLE_CHILDROLE_MAP" ADD CONSTRAINT "SECURITY_ROLE47_PK" PRIMARY KEY ("NAME_OID", "INTEGER_IDX");

ALTER TABLE "SA"."SECURITY_USERASSIGNMENT_ROLENAMES" ADD CONSTRAINT "SECURITY_USERDB_PK" PRIMARY KEY ("PRINCIPAL_OID", "INTEGER_IDX");

ALTER TABLE "SA"."SECURITY_ROLE_PERMISSION_MAP" ADD CONSTRAINT "SECURITY_ROLE16_PK" PRIMARY KEY ("NAME_OID", "INTEGER_IDX");

ALTER TABLE "SA"."SECURITY_OPERATIONS" ADD CONSTRAINT "SECURITY_OPERIU_PK" PRIMARY KEY ("NAME");

ALTER TABLE "SA"."SECURITY_USER_ASSIGNMENTS" ADD CONSTRAINT "SECURITY_USERE6_PK" PRIMARY KEY ("PRINCIPAL");

ALTER TABLE "SA"."SECURITY_RESOURCES" ADD CONSTRAINT "SECURITY_RESOR8_PK" PRIMARY KEY ("IDENTIFIER");

-- FOREIGN
ALTER TABLE "SA"."JDOUSER_PREVIOUSENCODEDPASSWORDS" ADD CONSTRAINT "JDOUSER_PREVJI_FK1" FOREIGN KEY ("USERNAME_OID") REFERENCES "SA"."JDOUSER" ("USERNAME") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "SA"."SECURITY_PERMISSIONS" ADD CONSTRAINT "SECURITY_PER5Q_FK1" FOREIGN KEY ("RESOURCE_IDENTIFIER_OID") REFERENCES "SA"."SECURITY_RESOURCES" ("IDENTIFIER") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "SA"."SECURITY_PERMISSIONS" ADD CONSTRAINT "SECURITY_PER5Q_FK2" FOREIGN KEY ("OPERATION_NAME_OID") REFERENCES "SA"."SECURITY_OPERATIONS" ("NAME") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "SA"."SECURITY_ROLE_CHILDROLE_MAP" ADD CONSTRAINT "SECURITY_ROLQ5_FK1" FOREIGN KEY ("NAME_OID") REFERENCES "SA"."SECURITY_ROLES" ("NAME") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "SA"."SECURITY_USERASSIGNMENT_ROLENAMES" ADD CONSTRAINT "SECURITY_USEXU_FK1" FOREIGN KEY ("PRINCIPAL_OID") REFERENCES "SA"."SECURITY_USER_ASSIGNMENTS" ("PRINCIPAL") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "SA"."SECURITY_ROLE_PERMISSION_MAP" ADD CONSTRAINT "SECURITY_ROLJY_FK1" FOREIGN KEY ("NAME_OID") REFERENCES "SA"."SECURITY_ROLES" ("NAME") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "SA"."SECURITY_ROLE_PERMISSION_MAP" ADD CONSTRAINT "SECURITY_ROLJY_FK2" FOREIGN KEY ("NAME_EID") REFERENCES "SA"."SECURITY_PERMISSIONS" ("NAME") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------------------------
-- DDL-Anweisungen für Überprüfungen
-- ----------------------------------------------

ALTER TABLE "SA"."JDOUSER" ADD CONSTRAINT "SQL221213070237493" CHECK (VALIDATED IN ('Y','N'));

ALTER TABLE "SA"."JDOUSER" ADD CONSTRAINT "SQL221213070237492" CHECK (PERMANENT IN ('Y','N'));

ALTER TABLE "SA"."JDOUSER" ADD CONSTRAINT "SQL221213070237491" CHECK (PASSWORD_CHANGE_REQUIRED IN ('Y','N'));

ALTER TABLE "SA"."JDOUSER" ADD CONSTRAINT "SQL221213070237490" CHECK (LOCKED IN ('Y','N'));

ALTER TABLE "SA"."SECURITY_ROLES" ADD CONSTRAINT "SQL221213070233841" CHECK (PERMANENT IN ('Y','N'));

ALTER TABLE "SA"."SECURITY_ROLES" ADD CONSTRAINT "SQL221213070233840" CHECK (ASSIGNABLE IN ('Y','N'));

ALTER TABLE "SA"."SECURITY_PERMISSIONS" ADD CONSTRAINT "SQL221213070234030" CHECK (PERMANENT IN ('Y','N'));

ALTER TABLE "SA"."SECURITY_OPERATIONS" ADD CONSTRAINT "SQL221213070233921" CHECK (RESOURCE_REQUIRED IN ('Y','N'));

ALTER TABLE "SA"."SECURITY_OPERATIONS" ADD CONSTRAINT "SQL221213070233920" CHECK (PERMANENT IN ('Y','N'));

ALTER TABLE "SA"."SECURITY_USER_ASSIGNMENTS" ADD CONSTRAINT "SQL221213070237240" CHECK (PERMANENT IN ('Y','N'));

ALTER TABLE "SA"."SECURITY_RESOURCES" ADD CONSTRAINT "SQL221213070233981" CHECK (PERMANENT IN ('Y','N'));

ALTER TABLE "SA"."SECURITY_RESOURCES" ADD CONSTRAINT "SQL221213070233980" CHECK (PATTERN IN ('Y','N'));

